# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/php@sha256:c3620fee1d114bb949e2ace7ff51207dd13d26c5af5aa8eecbc794562adbd61f

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update package repository
          command: sudo apt-get update
      - run:
         name: Install PHP libzip-dev
         command: sudo apt-get install -y libzip-dev libpng-dev
      - run:
         name: Install PHP Modules
         command: sudo docker-php-ext-install zip gd
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
          - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: composer unit

workflows:
  version: 2
  build_and_test:
    jobs:
    - build:
        context: Willow
